### ISSUE TITLE
Help installation failing 0.4.1-2

### ISSUE THREAD

**Issue by LabtronicsDesign** [tgalal/python-axolotl-curve25519#20]
The installation is failing and i have no idea how to fix. 

Has anyone experienced the same issue?

```
D:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:355: UserWarning: Normalizing '0.4.1-2' to '0.4.1.post2'
  normalized_version,
running install
running bdist_egg
running egg_info
writing python_axolotl_curve25519.egg-info\PKG-INFO
writing dependency_links to python_axolotl_curve25519.egg-info\dependency_links.txt
writing top-level names to python_axolotl_curve25519.egg-info\top_level.txt
reading manifest file 'python_axolotl_curve25519.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_axolotl_curve25519.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    platforms='any'
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 170, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 156, in call_command
    self.run_command(cmdname)
  File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\ProgramData\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "D:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "D:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```

How can I fix the TypeError? This is from a fresh install, haven't installed python-axolotl yet.

**Comment by LabtronicsDesign** [comment]
Fixed, first install `conda install mingw libpython` since im using Anaconda3.
Also use [TDM-GCC](http://tdm-gcc.tdragon.net/) instead of MinGW and this [video](https://www.youtube.com/watch?v=TLh--v8OxHE&) helped for those using VS Code
