### ISSUE TITLE
can't install on win10

### ISSUE THREAD

**Issue by xxXKraysXxx** [tgalal/python-axolotl-curve25519#24]
help pls :c
 ```
Running setup.py install for python-axolotl-curve25519: started
    Running setup.py install for python-axolotl-curve25519: finished with status 'error'
    Complete output from command "c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokeniz    e;__file__='C:\\Users\\CRAZYA~1\\AppData\\Local\\Temp\\pip-install-059v2u3q\\python-axolotl-curve25519\\setup.py';    f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fil    e__, 'exec'))" install --record C:\Users\CRAZYA~1\AppData\Local\Temp\pip-record-a_ujapqu\install-record.txt --sing    le-version-externally-managed --compile:
    c:\program files (x86)\python37-32\lib\site-packages\setuptools\dist.py:397: UserWarning: Normalizing '0.4.1-2    ' to '0.4.1.post2'
      normalized_version,
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CRAZYA~1\AppData\Local\Temp\pip-install-059v2u3q\python-axolotl-curve25519\setup.py", line 27    , in <module>
        platforms='any'
      File "c:\program files (x86)\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files (x86)\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files (x86)\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files (x86)\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files (x86)\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\program files (x86)\python37-32\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "c:\program files (x86)\python37-32\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "c:\program files (x86)\python37-32\lib\distutils\cygwinccompiler.py", line 282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "c:\program files (x86)\python37-32\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command ""c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\C    RAZYA~1\\AppData\\Local\\Temp\\pip-install-059v2u3q\\python-axolotl-curve25519\\setup.py';f=getattr(tokenize, 'ope    n', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install -    -record C:\Users\CRAZYA~1\AppData\Local\Temp\pip-record-a_ujapqu\install-record.txt --single-version-externally-ma    naged --compile" failed with error code 1 in C:\Users\CRAZYA~1\AppData\Local\Temp\pip-install-059v2u3q\python-axol    otl-curve25519\
```

**Comment by SalahAdDin** [comment]
Anyone know a solution for this problem?

**Comment by eneerbh** [comment]
same issue

    Running setup.py install for python-axolotl-curve25519 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\eneerbh\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\eneerbh\\AppData\\Local\\Temp\\pip-install-3yfdjtpq\\python-axolotl-curve25519\\setup.py'"'"'; __file__='"'"'C:\\Users\\eneerbh\\AppData\\Local\\Temp\\pip-install-3yfdjtpq\\python-axolotl-curve25519\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\eneerbh\AppData\Local\Temp\pip-record-8d4l4nfy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\eneerbh\appdata\local\programs\python\python38\Include\python-axolotl-curve25519'
         cwd: C:\Users\eneerbh\AppData\Local\Temp\pip-install-3yfdjtpq\python-axolotl-curve25519\
    Complete output (6 lines):
    c:\users\eneerbh\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py:469: UserWarning: Normalizing '0.4.1-2' to '0.4.1.post2'
      warnings.warn(
    running install
    running build
    running build_ext
    error: don't know how to compile C/C++ code on platform 'nt' with 'mingw32.exe' compiler
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\eneerbh\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\eneerbh\\AppData\\Local\\Temp\\pip-install-3yfdjtpq\\python-axolotl-curve25519\\setup.py'"'"'; __file__='"'"'C:\\Users\\eneerbh\\AppData\\Local\\Temp\\pip-install-3yfdjtpq\\python-axolotl-curve25519\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\eneerbh\AppData\Local\Temp\pip-record-8d4l4nfy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\eneerbh\appdata\local\programs\python\python38\Include\python-axolotl-curve25519' Check the logs for full command output.

C:\Users\eneerbh\AppData\Local\Programs\Python\Python38>

**Comment by matiasleoni** [comment]
I have the exact same issue.

**Comment by TasseDeCafe** [comment]
This issue is still not solved. I am getting the same error.
