### ISSUE TITLE
undefined references

### ISSUE THREAD

**Issue by bkoroglu** [tgalal/python-axolotl-curve25519#5]
Although I completed all installation instructions, the following error is seen when running python setup.py install  (Windows 8 64 bit)

build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
35): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
4d): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
58): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
73): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
7e): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
b2): undefined reference to`_imp__PyString_FromStringAndSize'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
106): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
11e): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
129): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
15d): undefined reference to`_imp__PyString_FromStringAndSize'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
191): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
1a9): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
1b4): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
1e4): undefined reference to`_imp__PyString_FromStringAndSize'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
237): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
253): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
25e): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
279): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
284): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
2c0): undefined reference to`_imp___Py_BuildValue_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
31a): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
336): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
341): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
35c): undefined reference to`_imp__PyExc_ValueError'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
367): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
3ab): undefined reference to`_imp__PyString_FromStringAndSize'
build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x
3ea): undefined reference to `_imp__Py_InitModule4'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: build\temp
.win-amd64-2.7\Release\curve25519module.o: bad reloc address 0x0 in section`.da
ta'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\MinGW\bin\gcc.exe' failed with exit status 1

**Comment by aesedepece** [comment]
Exactly same issue here on Python 2.7 32 bits Windows 7.

**Comment by aesedepece** [comment]
It installs flawlessly with Python 3.4 after doing:

```
easy_install https://github.com/axper/python3-pycrypto-windows-installer/raw/master/pycrypto-2.6.1.win32-py3.4.exe
python setup.py install
```

**Comment by bastronaut** [comment]
Hi, did you ever find a solution to this for python 2.7?

**Comment by dreamflasher** [comment]
Same issue here -- with Python 3.5 it works, with Python 2.7 it doesn't.

**Comment by alexisjk** [comment]
Now i am dealing whith :

`yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "C:\Users\Silvina\Desktop\yowsup-master\yowsup-master\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'

After Doing :**python yowsup-cli demos --config yowsup-cli.config --send xxxxxx “XXX”`**
I am Close now!

**Comment by hmrasi** [comment]
need some help regarding the axolotl curve.
I'm getting the error as
NoModuleFoundError : No Module named 'Axolotl_Curve25519'

anyone please help me?

**Comment by hmrasi** [comment]
g
